### PR TITLE
creation of workitem repository

### PR DESCRIPTION
**Pull request by tsurdilo**

### CODE REVIEW

**Comment by tsurdilo** [comment]
@mswiderski this does:
1. each module now uses org.jbpm.process.workitem.core.util.WidProcessor
2. each module assembles its own repository files
3. the "repository" module assembles each individual modules repo files and includes index.conf to build a full workitem repository structure which then can be uploaded wherever.

**Comment by tsurdilo** [comment]
@mswiderski this is what the results of building the repository module creates:

screen shot 2017-10-19 at 9 52 46 pm

**Comment by tsurdilo** [comment]
@mswiderski this is what the final repository looks like:

screen shot 2017-10-19 at 10 04 05 pm

**Comment by tsurdilo** [comment]
@mswiderski each directory includes structure like this (which is built by individual modules assembly)
screen shot 2017-10-19 at 9 52 59 pm

**Comment by tsurdilo** [comment]
@mswiderski no its not generated. i could not find a way to do this outside writing custom mojo for it. I think we could either remove this file as its use is rather limited (i don't see its use at all except some legacy integration really) or I could create a mojo that does this. Let me know what you would like to do here. Thanks!

**Comment by mswiderski** [comment]
@tsurdilo if there is no purpose for it in long run then I believe we should remove it

**Comment by tsurdilo** [comment]
@mswiderski ok sure ill remove it in next commit

**Pull request merged**
