### PR TITLE
[JBPM-9357] Add springboot Kafka WIH tests

### PR DESCRIPTION
**Pull request by gmunozfe**
**Thank you for submitting this pull request**

**JIRA**: [JBPM-9357](https://issues.redhat.com/browse/JBPM-9357)

Cherry picked from #157 

**referenced Pull Requests**:  
* [droolsjbpm-build-bootstrap#1487](https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1487)
* https://github.com/kiegroup/kie-jenkins-scripts/pull/826

### CODE REVIEW

**Comment by afalhambra** [comment]
Jenkins retest this

**Review by afalhambra — APPROVED** [review]
LGTM - just wait for CI build to go green

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by afalhambra** [comment]
jenkins retest this

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
hi @Ginxo, @mareknovotny,
this PR is failing due to timeout. I've seen that it's set to 1 hour, but with these new tests (which use TestContainers and need to download docker image of kafka) it's not enough:

```
15:48:19  Timeout set to expire in 1 hr 0 min
...
16:48:19  Cancelling nested steps due to timeout
16:48:19  Sending interrupt signal to process
```

Is it possible to increase timeout for PR build in this repo?

**Comment by Ginxo** [comment]
@gmunozfe @elguardian @mareknovotny @mbiarnes PR submitted to increase jbpm-work-items timeout https://github.com/kiegroup/kie-jenkins-scripts/pull/826
please check

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by elguardian** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by elguardian** [comment]
finally green.

**Comment by mareknovotny** [comment]
@elguardian you haven'ŧ merged also the linked PR here and now I found CDB build on another PR failing due missing the depMgmt added here. Can you merge the other PRs too?

**Pull request merged**
