### PR TITLE
Bump Spring Boot version to 2.2.1

### PR DESCRIPTION
**Pull request by cuijulian**
Depends on: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1086

### CODE REVIEW

**Comment by cuijulian** [comment]
@MarianMacik The build fails with this error:

`[ERROR] Non-resolvable import POM: Could not find artifact org.springframework.boot:spring-boot-dependencies:pom:${version.org.springframework.boot} in mirror-central (http://bxms-qe.rhev-ci-vms.eng.rdu2.redhat.com:8081/nexus/content/groups/public/) @ org.jbpm.contrib:repository-springboot:[unknown-version], /home/jenkins/workspace/KIE/master/pullrequest/jbpm-work-items-pullrequests/repository-springboot/pom.xml, line 25, column 19`

It seems the dependency version `${version.org.springframework.boot}` is not recognized, even though it is declared in `kie-parent`, which is found in the PR linked above. Running `mvn clean install -Dfull` on this PR works for two of my machines, so I'm not sure why Jenkins is failing. Am I missing something?

**Comment by MarianMacik** [comment]
@cuijulian I think that is because this repository doesn't compile upstream repositories like droolsjbpm-build-bootstrap. So we will have to wait until the kie-parent is merged and then this will start working. Am I correct @mareknovotny ?

**Comment by mareknovotny** [comment]
@MarianMacik yes, that is not configured see the exclusion for this repository https://github.com/kiegroup/kie-jenkins-scripts/blob/master/job-dsls/jobs/pr_jobs.groovy#L242-L244

**Comment by mareknovotny** [comment]
Jenkins retest this please

**Comment by ge0ffrey** [comment]
Jenkins retest this.

**Pull request merged**
