### PR TITLE
JBPM-8398 - Kafka WIH org.apache.kafka.common.serialization.StringSerializer could not be found

### PR DESCRIPTION
**Pull request by paulomenon**
I'm fixing a bug that I got on workbench to use this work item handler, happened on both 7.19 and 7.20 version of the work item handler.
Workbench version 7.19
More details on the jira JBPM-8398

### CODE REVIEW

**Comment by kie-ci9** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by tsurdilo** [comment]
@paulomenon we need a test added for this change. setting setContextClassLoader to null may affect process execution after the workitem handler completes. could you please add a test for this scenario?

**Comment by tsurdilo** [comment]
You could also try to add the kafla-clients jar dependency in your project. Then the missing class should be found.

**Comment by sharma-sudhakar** [comment]
@tsurdilo thanks for your comments, I tried adding kafka-client dependency as well as whitelisting kafka-client packages but no luck. I am new in JBPM and I am facing this issue on 7.40.0.Final. This is working on jbpm business application but not working inside business-central. Could you please suggest another workaround?

**Comment by sharma-sudhakar** [comment]
Used `Thread.currentThread().setContextClassLoader(org.apache.kafka.clients.consumer.KafkaConsumer.class.getClassLoader());` as has been done in a workaround in [Apache-Camel](https://github.com/apache/camel/commit/83c3e86d5db7f6429fb5e7f262c8f23dd4ddaf25) earlier they have used setting up null context which raised another issue while using secured communication with kafka [this commit](https://github.com/apache/camel/commit/eba0e077e6b38c4d01eb22b13816aae99d4819a4). I ended up with the following exception when using null context.

**Comment by tsurdilo** [comment]
@sharma-sudhakar hmm nice comments. so what do you suggest to be done?

**Comment by sharma-sudhakar** [comment]
@tsurdilo, The [commit](https://github.com/apache/camel/commit/83c3e86d5db7f6429fb5e7f262c8f23dd4ddaf25), I referenced is working for me and in Apache-Camel. We could include all possible test scenarios and include the changes in WID.

**Comment by elguardian** [comment]
this is already fixed in here
https://github.com/kiegroup/jbpm-work-items/commit/69062e8a50a3e01311c3a2ac82b8687a550caf1f

**Comment by pamenon** [comment]
Which version this fix was target ?

**Comment by mareknovotny** [comment]
@pamenon the commit is included in 7.44.0.Final tag

**Pull request closed without merging**
