### PR TITLE
[7.59.x][JBPM-9940] - Kafka WIH tests are failing due to "EntityManagerFactory is closed"

### PR DESCRIPTION
**Pull request by afalhambra**
Backport of https://github.com/kiegroup/jbpm-work-items/pull/224

### CODE REVIEW

**Comment by afalhambra** [comment]
@gmunozfe can you please have a look? thanks!

**Review by gmunozfe — APPROVED** [review]
Looks good to me, way to go @afalhambra !

**Comment by afalhambra** [comment]
Jenkins retest this

**Comment by Ginxo** [comment]
Jenkins retest this

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
