### PR TITLE
JBPM-8102 - Update workitems definitions in repository

### PR DESCRIPTION
**Pull request by tsurdilo**
** depends on https://github.com/kiegroup/jbpm/pull/1408 **

* adds icon setting to each handler
* updates wid processor settings to generate wid for each handler
* adds link to individual handler wid (for download) on repo site:

screen shot 2019-01-03 at 1 21 26 pm

### CODE REVIEW

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
jenkins build for jbpm-work-items seems broke (it does not check other commits with same branch name) so we will need for kiegroup/jbpm#1408 to get committed first then retest this...

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mswiderski** [comment]
replaced with https://github.com/kiegroup/jbpm-work-items/pull/88

**Pull request closed without merging**
