### PR TITLE
[JBPM-9665] Add tests for default Kafka WIH

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: [JBPM-9665](https://issues.redhat.com/browse/JBPM-9665)

### CODE REVIEW

**Comment by gmunozfe** [comment]
@elguardian just adding simple unit tests for testing defaults in new kafka wih constructors

**Comment by gmunozfe** [comment]
@afalhambra please, review it, thx!

**Review by afalhambra — APPROVED** [review]
Awesome job, nice done @gmunozfe

**Review by tsurdilo — APPROVED** [review]

**Comment by gmunozfe** [comment]
@mareknovotny @tsurdilo, could you please merge? thanks!

**Pull request merged**
