### PR TITLE
[JBPM-9453] Exclusions needed at spring-boot-starter-test after bumping to junit 4.13.1

### PR DESCRIPTION
**Pull request by gmunozfe**
**JIRA**: [JBPM-9453](https://issues.redhat.com/browse/JBPM-9453)

### CODE REVIEW

**Comment by gmunozfe** [comment]
Same as https://github.com/kiegroup/droolsjbpm-integration/pull/2303

@MarianMacik could you review?

**Review by MarianMacik — APPROVED** [review]

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by gmunozfe** [comment]
jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Pull request closed without merging**
