### PR TITLE
BAPL-1148: upgraded to jboss-jaxrs-api_2.1_spec

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by mbiarnes** [comment]
merge together..:
https://github.com/errai/errai/pull/378
https://github.com/kiegroup/kie-soup/pull/82
https://github.com/kiegroup/appformer/pull/648
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/933
https://github.com/kiegroup/optaplanner/pull/488
https://github.com/kiegroup/jbpm/pull/1450
https://github.com/kiegroup/droolsjbpm-integration/pull/1749
https://github.com/kiegroup/kie-wb-common/pull/2501
https://github.com/kiegroup/jbpm-wb/pull/1305
https://github.com/kiegroup/jbpm-work-items/pull/97
https://github.com/kiegroup/kie-docs/pull/1414
https://github.com/kiegroup/kie-wb-distributions/pull/883
https://github.com/kiegroup/optaweb-employee-rostering/pull/229

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
@mareknovotny the build fails because of a bunch of duplicated classes found - this didn't pass nor on Jenkins nor on my local. Could you have a look?

**Comment by mareknovotny** [comment]
@mbiarnes because there are still classes from the upgraded GAV in test scope
```
  Found in:
    org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.0_spec:jar:1.0.0.Final:test
    org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec:jar:1.0.1.Final:compile
```
change them to be 2.1 too

**Comment by mbiarnes** [comment]
@mareknovotny the only places were I find jboss-jaxrs-api_2.0_spec are in https://github.com/kiegroup/jbpm-work-items/search?q=jboss-jaxrs-api_2.0_spec&unscoped_q=jboss-jaxrs-api_2.0_spec, and I changed them in this PR

**Comment by mareknovotny** [comment]
I can see it is a transitive dependency:

```xml
diff --git a/ifttt-workitem/pom.xml b/ifttt-workitem/pom.xml
index 84c9687..00b4760 100644
--- a/ifttt-workitem/pom.xml
+++ b/ifttt-workitem/pom.xml
@@ -19,7 +19,7 @@
   <dependencies>
     <dependency>
       <groupId>org.jboss.spec.javax.ws.rs</groupId>
-      <artifactId>jboss-jaxrs-api_2.0_spec</artifactId>
+      <artifactId>jboss-jaxrs-api_2.1_spec</artifactId>
     </dependency>
     <dependency>
       <groupId>com.fasterxml.jackson.core</groupId>
@@ -90,6 +90,10 @@
           <groupId>javax.activation</groupId>
           <artifactId>activation</artifactId>
         </exclusion>
+       <exclusion>
+               <groupId>org.jboss.spec.javax.ws.rs</groupId>
+               <artifactId>jboss-jaxrs-api_2.0_spec</artifactId>
+       </exclusion>
       </exclusions>
     </dependency>
     <dependency>
```

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
@mareknovotny build was successful but two test failed (same test than in dailyBuilds)

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Comment by mbiarnes** [comment]
@tsurdilo can you please look at these [2 failing tests](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/jbpm-work-items-pullrequests/109/testReport/) (they also fail in dailyBuilds master)

**Comment by mbiarnes** [comment]
Jenkins please retest this

**Pull request merged**
