### PR TITLE
[JBPM-9711] JbpmJUnitBaseTestCase no longer uses default datasource properties

### PR DESCRIPTION
**Pull request by afalhambra**
**[JBPM-9711](https://issues.redhat.com/browse/JBPM-9711)**: JbpmJUnitBaseTestCase no longer uses default datasource properties

depends on https://github.com/kiegroup/jbpm/pull/1923

### CODE REVIEW

**Comment by afalhambra** [comment]
@gmunozfe - I don't know why but I cannot add you as a reviewer here. Can you please have a look? Thanks!

**Comment by gmunozfe** [comment]
jenkins test this

**Review by gmunozfe — APPROVED** [review]
Looks good to me, nice work @afalhambra !

**Comment by afalhambra** [comment]
@mareknovotny please merge, thanks

**Pull request merged**
