### PR TITLE
Exclude duplicated dependency org.ow2.asm:asm

### PR DESCRIPTION
**Pull request by jomarko**
Hi Team, we currently do not have master nightly builds, due to the error bellow. Could someone have a look if this fix the problem?
[error.log](https://github.com/kiegroup/jbpm-work-items/files/3119807/error.log)

### CODE REVIEW

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by mbiarnes** [comment]
@jomarko @mareknovotny cherry-picked this PR for testing it. Works! It worked on Jenkins too. The failed test has nothing to do with jbpm-work-items. The failed test is related to droolsjbpm-integration.
+1 to merge

**Comment by mareknovotny** [comment]
I will let @tsurdilo review too

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Comment by jomarko** [comment]
jenkins execute full downstream build

**Pull request merged**
