### PR TITLE
JBPM-8417 - Add Insert/Update/Delete query capability to ExecuteSqlWorkItemHandler

### PR DESCRIPTION
**Pull request by jcavieres**
"executeQuery" doesn't allow querys that could change the Database (Insert,Update...)
I changed it for "execute" and added a test for that case.

### CODE REVIEW

**Comment by kie-ci9** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by tsurdilo** [comment]
ok to test

**Comment by tsurdilo** [comment]
@jcavieres looks good to me, could you please format the code? thanks.

**Comment by tsurdilo** [comment]
will merge after build green

**Pull request merged**
