### PR TITLE
[7.33.x] Fix import statement for downgrade to Spring 5.1.13

### PR DESCRIPTION
**Pull request by cuijulian**
Merge with:

https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1196
https://github.com/kiegroup/optaplanner/pull/701
https://github.com/kiegroup/optaweb-employee-rostering/pull/397
https://github.com/kiegroup/optaweb-vehicle-routing/pull/270

### CODE REVIEW

**Comment by MarianMacik** [comment]
jbpm-work-items doesn't see changes from other repositories. It should start working after droolsjbpm-build-bootstrap is merged.

**Comment by cuijulian** [comment]
@MarianMacik Normally yes, but in this case there's a downgrade of the Spring dependency that this repository depends on, which slightly altered a Spring import statement. This change was necessary to stop the downstream build from failing.

**Comment by MarianMacik** [comment]
@cuijulian sure, I am not questioning the necessity of this change. I just wanted to add a note here that it is expected that it failed.

**Comment by cuijulian** [comment]
@MarianMacik Ah, sorry I misunderstood your comment :P. Yes, absolutely, your comment explains why the build fails on this repo. Thanks for the clarification :)

**Pull request merged**
