### PR TITLE
AF-2736 Fix jbpm-work-items CamelWorkitemIntegrationTest

### PR DESCRIPTION
**Pull request by bxf12315**
**Thank you for submitting this pull request**

**JIRA**: _(please edit the JIRA link if it exists)_ 

[AF-2736](https://issues.redhat.com/browse/AF-2736)

**referenced Pull Requests**: _(please edit the URLs of referenced pullrequests if they exist)_

* paste the link(s) from GitHub here
* link 2
* link 3 etc.

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by bxf12315** [comment]
Jenkins run fdb

**Comment by mareknovotny** [comment]
jenkins retest this please

**Review by jiripetrlik — CHANGES_REQUESTED** [review]
@bxf12315 @mareknovotny 
I don't think it is a good idea to ignore this test completely. Maybe we can take the same approach as in https://github.com/kiegroup/droolsjbpm-integration/pull/2366/files

**Comment by mareknovotny** [comment]
there were introduced a profile activating on jdk version. This can be safely closed.

**Pull request closed without merging**
