### PR TITLE
JBPM-8010 - Add Authentication info to @wid annotation

### PR DESCRIPTION
**Pull request by tsurdilo**
* adds handler constructor parameters to wid annotation for all handlers which take parameters
* adds authentication info for all handlers to the wid annotation
* updates index page, docs page and service.js to include the authentication information
*formats all handlers and some xml too

### CODE REVIEW

**Comment by tsurdilo** [comment]
@mswiderski sorry larger change :) i think this info is very important when we start building the workbench repository integration as before users would not have info about auth and the handler constructor parameters in the wid

**Comment by tsurdilo** [comment]
depends on https://github.com/kiegroup/jbpm/pull/1384

**Comment by tsurdilo** [comment]
need to update to use reference site instead of auth site

**Comment by tsurdilo** [comment]
@mswiderski updated for referencesite

**Comment by tsurdilo** [comment]
@mswiderski do you mean the definition in the wid? For most workitems especially the ones that take in auth the definition assumed some default constructor which did not exist and it was wrong. Now still some workitems that did use default constructor use it but it was fixed where the generated wid actually reflects the handler parameters which users have to specify for cases where using the default constructor is either wrong or one does not exist.

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
had to update to fix deployment descriptor parameters - now depends on 

https://github.com/kiegroup/jbpm/pull/1388

since i cant match branch names this build will fail until we merge
https://github.com/kiegroup/jbpm/pull/1388
sorry

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
@mswiderski added one more change -- https://github.com/kiegroup/jbpm-work-items/pull/81/files#diff-600376dffeb79835ede4a0b285078036R73

we use 

<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.5.12.RELEASE</version>
  </parent>

in our generated business apps which uses the older version of kafka. If we dont align there are a ton of classnotfounds if trying to run the kafka workitem in business app. This aligns it.

**Comment by mswiderski** [comment]
@tsurdilo I'd say we should not change the version here but rather upgrade it on the business app level, override the version of Kafka used by spring boot dependencies project instead.

**Comment by tsurdilo** [comment]
@mswiderski ok that makes more sense. will do. reverted that change. should be good now

**Pull request merged**
