### PR TITLE
[7.44.x] fix integration tests due to kafka change 

### PR DESCRIPTION
**Pull request by jstastny-cz**
Cherry-pick of #155 

**JIRA**:
[JBPM-9398](https://issues.redhat.com/browse/JBPM-9398)

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by elguardian** [comment]
Jenkins retest this please.

**Review by MarianMacik — APPROVED** [review]

**Comment by afalhambra** [comment]
I believe this is no longer need as this is already include in PR https://github.com/kiegroup/jbpm-work-items/pull/157

**Pull request closed without merging**
