### PR TITLE
[JBPM-9436] AMQ Streams (Kafka) listener functionality / consumer

### PR DESCRIPTION
**Pull request by fjtirado**
Changing work item compilation scope, since Kafka dependency will be now
part of kie server

Merge with [#droolsjbpm-integration:2288](https://github.com/kiegroup/droolsjbpm-integration/pull/2288)

[JBPM-9436](https://issues.redhat.com/browse/JBPM-9436)

### CODE REVIEW

**Review by afalhambra — APPROVED** [review]
Looks good - just a request if you can :)

Would be good to remove this from the pom.xml but up to you

https://github.com/kiegroup/jbpm-work-items/blob/665bb75b39d009070987b1f6c02177f178893cc3/kafka-workitem/pom.xml#L11-L13

**Comment by elguardian** [comment]
this is ok.
Jenkins retest this please.

**Review by elguardian — APPROVED** [review]

**Comment by elguardian** [comment]
Jenkins retest this

**Comment by elguardian** [comment]
Jenkin retest this please

**Comment by elguardian** [comment]
Jenkin retest this

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by elguardian** [comment]
Jenkins retest this please.

**Comment by elguardian** [comment]
Jenkins retest this

**Review by gmunozfe — APPROVED** [review]
Looks good to me, well done @fjtirado !

**Pull request merged**
