### PR TITLE
fixed org.jbpm.contrib:repository deprecated properties for artifactI…

### PR DESCRIPTION
**Pull request by mareknovotny**
Just fixing repository/pom.xml for org.jbpm.contrib:repository to dismiss Maven warnings

<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>

* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
 
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
  
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>

* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>

* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>

### CODE REVIEW

**Comment by mareknovotny** [comment]
the failed flaky test reported as https://issues.redhat.com/browse/JBPM-9765

**Comment by elguardian** [comment]
not working.

**Comment by mareknovotny** [comment]
what's not working @elguardian ? Could you be more specific?

**Comment by elguardian** [comment]
@mareknovotny wrong comment in the wrong issue... too many tabs open. apologise

**Comment by mareknovotny** [comment]
@elguardian no problem, i was just unsure what is not working  ;).

**Review by elguardian — APPROVED** [review]

**Pull request merged**
