### PR TITLE
workitem handlers integration tests

### PR DESCRIPTION
**Pull request by tsurdilo**
adds integration test for each of the workitems in repository. depends on https://github.com/kiegroup/jbpm/pull/1101

### CODE REVIEW

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
for some reason jenkins is now not using the changes in kiegroup/jbpm#1101 even tho branches have same name. will wait to retest after that pr is merged...

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by mswiderski** [comment]
Jenkins retest this

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins execute full downstream build

**Comment by tsurdilo** [comment]
@psiroky if you have time could you please take a look? This builds locally with -Dfull without issues but here the changes of commit https://github.com/kiegroup/jbpm/commit/588ddc69ecb5bb38de9cbcf59574e4f1e50d1125 are not being picked up. Do you see any reason why this would be?

**Comment by tsurdilo** [comment]
going to run retest couple more times to make sure its ok

**Comment by tsurdilo** [comment]
Jenkins retest please

**Comment by tsurdilo** [comment]
Jenkins retest please

**Pull request merged**
